mUnited = Team.create(name:"Manchester United")
mCity = Team.create(name:"Manchester City")
astonVilla = Team.create(name:"Aston Villa")
westHam = Team.create(name:"West Ham United")
leeds = Team.create(name:"Leeds United")
chelsea = Team.create(name:"Chelsea")
liverpool = Team.create(name:"Liverpool")
tottenham = Team.create(name:"Tottenham")
arsenal = Team.create(name:"Arsenal FC")
leicester = Team.create(name:"Leicester City")
brighton = Team.create(name:"Brighton and Hove")
wolves = Team.create(name:"Wolveshampton")
newcastle = Team.create(name:"Newclaste")
crystalPalace = Team.create(name:"Crystal Palace")
brentford = Team.create(name:"Brentford")
southampton = Team.create(name:"Southampton")
everton = Team.create(name:"Everton")
fulham = Team.create(name:"Fulham")
bournemouth = Team.create(name:"Bournemouth")
nottingham = Team.create(name:"Nottingham Forest")
Match.create(local:fulham, visitor: everton, date:1)
Match.create(local:mUnited, visitor: wolves, date:1)
Match.create(local:mCity, visitor: liverpool, date:1)
Match.create(local:chelsea, visitor: crystalPalace, date:1)
Match.create(local:newcastle, visitor: astonVilla, date:1)
Match.create(local:brighton, visitor: arsenal, date:1)
Match.create(local:leicester, visitor: nottingham, date:1)
Match.create(local:bournemouth, visitor: southampton, date:1)
Match.create(local:liverpool, visitor: westHam, date:1)
Match.create(local:brentford, visitor: tottenham, date:1)
Match.create(local:fulham, visitor: tottenham, date:2)
Match.create(local:westHam, visitor: wolves, date:2)
Match.create(local:mCity, visitor: bournemouth, date:2)
Match.create(local:leicester, visitor: crystalPalace, date:2)
Match.create(local:arsenal, visitor: astonVilla, date:2)
Match.create(local:brighton, visitor: newcastle, date:2)
Match.create(local:chelsea, visitor: nottingham, date:2)
Match.create(local:leeds, visitor: southampton, date:2)
Match.create(local:liverpool, visitor: mUnited, date:2)
Match.create(local:brentford, visitor: everton, date:2)
Match.create(local:brentford, visitor:leeds, date:3)
Match.create(local:chelsea, visitor:liverpool, date:3)
Match.create(local:arsenal, visitor:wolves, date:3)
Match.create(local:brighton, visitor:fulham, date:3)
Match.create(local:nottingham, visitor:mCity, date:3)
Match.create(local:bournemouth, visitor:westHam, date:3)
Match.create(local:tottenham, visitor:astonVilla, date:3)
Match.create(local:everton, visitor:crystalPalace, date:3)
Match.create(local:newcastle, visitor:mUnited, date:3)
Match.create(local:leicester, visitor:southampton, date:3)
Match.create(local:arsenal, visitor:nottingham, date:4)
Match.create(local:bournemouth, visitor:tottenham, date:4)
Match.create(local:everton, visitor:newcastle, date:4)
Match.create(local:leicester, visitor:leeds, date:4)
Match.create(local:liverpool, visitor:wolves, date:4)
Match.create(local:fulham, visitor:mCity, date:4)
Match.create(local:westHam, visitor:astonVilla, date:4)
Match.create(local:brighton, visitor:crystalPalace, date:4)
Match.create(local:mUnited, visitor:southampton, date:4)
Match.create(local:brentford, visitor:chelsea, date:4)
Match.create(local:nottingham, visitor:bournemouth, date:5)
Match.create(local:mUnited, visitor:nottingham, date:17)
Match.create(local:nottingham, visitor:astonVilla, date:19)
Match.create(local:westHam, visitor:nottingham, date:8)
Match.create(local:nottingham, visitor:leeds, date:9)
Match.create(local:nottingham, visitor:liverpool, date:10)
Match.create(local:tottenham, visitor:nottingham, date:11)
Match.create(local:nottingham, visitor:brighton, date:12)
Match.create(local:wolves, visitor:nottingham, date:13)
Match.create(local:newcastle, visitor:nottingham, date:14)
Match.create(local:nottingham, visitor:crystalPalace, date:15)
Match.create(local:brentford, visitor:nottingham, date:16)
Match.create(local:nottingham, visitor:everton, date:6)
Match.create(local:southampton, visitor:nottingham, date:18)
Match.create(local:nottingham, visitor:fulham, date:19)
Match.create(local:bournemouth, visitor:mUnited, date:6)
Match.create(local:bournemouth, visitor:astonVilla, date:7)
Match.create(local:leeds, visitor:bournemouth, date:8)
Match.create(local:bournemouth, visitor:chelsea, date:9)
Match.create(local:bournemouth, visitor:liverpool, date:10)
Match.create(local:arsenal, visitor:bournemouth, date:11)
Match.create(local:bournemouth, visitor:leicester, date:12)
Match.create(local:brighton, visitor:bournemouth, date:13)
Match.create(local:bournemouth, visitor:wolves, date:14)
Match.create(local:newcastle, visitor:bournemouth, date:15)
Match.create(local:bournemouth, visitor:crystalPalace, date:16)
Match.create(local:everton, visitor:bournemouth, date:17)
Match.create(local:bournemouth, visitor:brentford, date:18)
Match.create(local:fulham, visitor:bournemouth, date:19)
Match.create(local:mUnited, visitor:mCity, date:7)
Match.create(local:astonVilla, visitor:mUnited, date:16)
Match.create(local:mUnited, visitor:westHam, date:9)
Match.create(local:leeds, visitor:mUnited, date:10)
Match.create(local:mUnited, visitor:chelsea, date:11)
Match.create(local:mUnited, visitor:tottenham, date:12)
Match.create(local:arsenal, visitor:mUnited, date:13)
Match.create(local:mUnited, visitor:leicester, date:14)
Match.create(local:brighton, visitor:mUnited, date:15)
Match.create(local:crystalPalace, visitor:mUnited, date:16)
Match.create(local:mUnited, visitor:brentford, date:5)
Match.create(local:everton, visitor:mUnited, date:18)
Match.create(local:mUnited, visitor:fulham, date:19)
Match.create(local:mCity, visitor:newcastle, date:5)
Match.create(local:southampton, visitor:mCity, date:6)
Match.create(local:mCity, visitor:astonVilla, date:8)
Match.create(local:westHam, visitor:mCity, date:9)
Match.create(local:mCity, visitor:leeds, date:10)
Match.create(local:mCity, visitor:chelsea, date:11)
Match.create(local:mCity, visitor:tottenham, date:12)
Match.create(local:arsenal, visitor:mCity, date:13)
Match.create(local:leicester, visitor:mCity, date:14)
Match.create(local:mCity, visitor:brighton, date:15)
Match.create(local:wolves, visitor:mCity, date:16)
Match.create(local:crystalPalace, visitor:mCity, date:17)
Match.create(local:mCity, visitor:brentford, date:18)
Match.create(local:everton, visitor:mCity, date:19)
Match.create(local:astonVilla, visitor:leeds, date:9)
Match.create(local:chelsea, visitor:astonVilla, date:10)
Match.create(local:liverpool, visitor:astonVilla, date:11)
Match.create(local:astonVilla, visitor:leicester, date:12)
Match.create(local:brighton, visitor:astonVilla, date:13)
Match.create(local:astonVilla, visitor:wolves, date:14)
Match.create(local:crystalPalace, visitor:astonVilla, date:15)
Match.create(local:brentford, visitor:astonVilla, date:5)
Match.create(local:astonVilla, visitor:everton, date:17)
Match.create(local:astonVilla, visitor:southampton, date:18)
Match.create(local:fulham, visitor:astonVilla, date:6)
