user01 = User.create(name: "juan", total_score: 0)
user02 = User.create(name: "mario", total_score: 0)
user03 = User.create(name: "elias", total_score: 0)
user04 = User.create(name: "martin", total_score: 0)
partido1 = Match.find_by()